---
server.name: kibana
server.host: "0.0.0.0"
server.port: 5601
elasticsearch.hosts: ["http://elasticsearch:9200"]
monitoring.ui.container.elasticsearch.enabled: true
xpack.security.enabled: false
xpack.encryptedSavedObjects.encryptionKey: "threat-hunting-lab-encryption-key-2024-minimum-32-chars"
