[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:sshd]
command=/usr/sbin/sshd -D
autostart=true
autorestart=true

[program:vnc]
command=bash -c "vncserver :1 -geometry 1280x800 -depth 24 -localhost no -fg"
autostart=true
autorestart=true

[program:novnc]
command=/opt/noVNC/utils/websockify/run --web /opt/noVNC 6901 localhost:5901
autostart=true
autorestart=true
startretries=5
